Update Dockerfile

diff --git a/ansible/Dockerfile b/ansible/Dockerfile
--- a/ansible/Dockerfile
+++ b/ansible/Dockerfile
@@ -1,5 +1,62 @@
-FROM alpine:3.7# 1. Use any image as your base image, or "scra      tch"# 2. Add fwatchdog binary via https://github.com/openfaas/faas/rel  eases/# 3. Then set fprocess to the process you want to invoke per req  uest - i.e. "cat" or "my_binary"#ADD https://github.com/openfaas/faas       /releases/download/0.8.0/fwatchdog /usr/bin#RUN chmod +x /usr/bin/fwat    chdogRUN mkdir -p /home/appRUN apk --no-cache add curl \    && ech                  o "Pulling watchdog binary from Github." \
-    && curl -sSL https://git    hub.com/openfaas/faas/releases/download/0.8.0/fwatchdog > /usr/bin/fwatchdog \    && chmod +x /usr/bin/fwatchdog \    && cp /usr/bin/fwatchdog /home/       app             RUN echo "===> Installing sudo to emulate normal OS behavior..."  && \    apk --update add sudo                                         && \           \    \    echo "===> Adding Python runtime..."  && \    apk --upda         te add python py-pip
-    openssl ca-certificates    && \    apk --update a   dd --virtual build-dependencies \                python-dev libffi-dev     openssl-dev build-base  && \    pip install --upgrade pip cffi                              && \    \    \    echo "===> Installing Ansible            ..."  && \    pip install ansible                && \    \    \                    echo "===> Installing handy tools (not absolutely required)..."  && \      pip install --upgrade pywinrm
-    && \    apk --update     add sshpass openssh-client rsync  && \    \    \    echo "===> Remo            ving package list..."  && \    apk del build-dependencies            & & \    rm -rf /var/cache/apk/*               && \    \    \    echo              "===> Adding hosts for convenience..."  && \    mkdir -p /etc/ansible                          && \    echo 'localhost' > /etc/ansible/hosts                # Add non root userRUN addgroup -S app && adduser -S -g app
-    app             RUN chown app /home/appWORKDIR /home/appUSER app# Populate examp                        le here - i.e. "cat", "sha512sum" or "node index.js"ENV fprocess="cat"       # Set to true to see request in function logsENV write_debug="false"            HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock  ] || exit 1CMD [ "fwatc    hdog"  ]
+FROM alpine:3.7
+
+# 1. Use any image as your base image, or "scratch"
+# 2. Add fwatchdog binary via https://github.com/openfaas/faas/releases/
+# 3. Then set fprocess to the process you want to invoke per request - i.e. "cat" or "my_binary"
+
+#ADD https://github.com/openfaas/faas/releases/download/0.8.0/fwatchdog /usr/bin
+#RUN chmod +x /usr/bin/fwatchdog
+
+RUN mkdir -p /home/app
+
+RUN apk --no-cache add curl \
+    && echo "Pulling watchdog binary from Github." \
+    && curl -sSL https://github.com/openfaas/faas/releases/download/0.8.0/fwatchdog > /usr/bin/fwatchdog \
+    && chmod +x /usr/bin/fwatchdog \
+    && cp /usr/bin/fwatchdog /home/app
+
+RUN echo "===> Installing sudo to emulate normal OS behavior..."  && \
+    apk --update add sudo                                         && \
+    \
+    \
+    echo "===> Adding Python runtime..."  && \
+    apk --update add python py-pip openssl ca-certificates    && \
+    apk --update add --virtual build-dependencies \
+                python-dev libffi-dev openssl-dev build-base  && \
+    pip install --upgrade pip cffi                            && \
+    \
+    \
+    echo "===> Installing Ansible..."  && \
+    pip install ansible                && \
+    \
+    \
+    echo "===> Installing handy tools (not absolutely required)..."  && \
+    pip install --upgrade pywinrm                  && \
+    apk --update add sshpass openssh-client rsync  && \
+    \
+    \
+    echo "===> Removing package list..."  && \
+    apk del build-dependencies            && \
+    rm -rf /var/cache/apk/*               && \
+    \
+    \
+    echo "===> Adding hosts for convenience..."  && \
+    mkdir -p /etc/ansible                        && \
+    echo 'localhost' > /etc/ansible/hosts
+# Add non root user
+
+RUN addgroup -S app && adduser -S -g app app
+
+RUN chown app /home/app
+
+WORKDIR /home/app
+
+USER app
+
+# Populate example here - i.e. "cat", "sha512sum" or "node index.js"
+ENV fprocess="cat"
+# Set to true to see request in function logs
+ENV write_debug="false"
+
+HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1
+CMD [ "fwatchdog" ]
